// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: tag.proto

package tag

import (
	"poetry/pb/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        []*common.Filter       `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTagRequest) Reset() {
	*x = DescribeTagRequest{}
	mi := &file_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTagRequest) ProtoMessage() {}

func (x *DescribeTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTagRequest.ProtoReflect.Descriptor instead.
func (*DescribeTagRequest) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeTagRequest) GetFilter() []*common.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DescribeTagRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DescribeTagRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TagInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Level         int64                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagInfo) Reset() {
	*x = TagInfo{}
	mi := &file_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagInfo) ProtoMessage() {}

func (x *TagInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagInfo.ProtoReflect.Descriptor instead.
func (*TagInfo) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TagInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TagInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type DescribeTagInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	TagInfoList   []*TagInfo             `protobuf:"bytes,2,rep,name=tagInfoList,proto3" json:"tagInfoList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTagInfoResponse) Reset() {
	*x = DescribeTagInfoResponse{}
	mi := &file_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTagInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTagInfoResponse) ProtoMessage() {}

func (x *DescribeTagInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTagInfoResponse.ProtoReflect.Descriptor instead.
func (*DescribeTagInfoResponse) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeTagInfoResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DescribeTagInfoResponse) GetTagInfoList() []*TagInfo {
	if x != nil {
		return x.TagInfoList
	}
	return nil
}

var File_tag_proto protoreflect.FileDescriptor

const file_tag_proto_rawDesc = "" +
	"\n" +
	"\ttag.proto\x12\vtrpc.poetry\x1a\x1dtrpc/proto/trpc_options.proto\x1a\fcommon.proto\"j\n" +
	"\x12DescribeTagRequest\x12&\n" +
	"\x06filter\x18\x01 \x03(\v2\x0e.common.FilterR\x06filter\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"_\n" +
	"\aTagInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x03R\x05level\"g\n" +
	"\x17DescribeTagInfoResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x126\n" +
	"\vtagInfoList\x18\x02 \x03(\v2\x14.trpc.poetry.TagInfoR\vtagInfoList2|\n" +
	"\x03Tag\x12u\n" +
	"\x0fDescribeTagInfo\x12\x1f.trpc.poetry.DescribeTagRequest\x1a$.trpc.poetry.DescribeTagInfoResponse\"\x1b\x8a\xb5\x18\x17/poetry/DescribeTagInfoB\bZ\x06pb/tagb\x06proto3"

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData []byte
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)))
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tag_proto_goTypes = []any{
	(*DescribeTagRequest)(nil),      // 0: trpc.poetry.DescribeTagRequest
	(*TagInfo)(nil),                 // 1: trpc.poetry.TagInfo
	(*DescribeTagInfoResponse)(nil), // 2: trpc.poetry.DescribeTagInfoResponse
	(*common.Filter)(nil),           // 3: common.Filter
}
var file_tag_proto_depIdxs = []int32{
	3, // 0: trpc.poetry.DescribeTagRequest.filter:type_name -> common.Filter
	1, // 1: trpc.poetry.DescribeTagInfoResponse.tagInfoList:type_name -> trpc.poetry.TagInfo
	0, // 2: trpc.poetry.Tag.DescribeTagInfo:input_type -> trpc.poetry.DescribeTagRequest
	2, // 3: trpc.poetry.Tag.DescribeTagInfo:output_type -> trpc.poetry.DescribeTagInfoResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_proto_rawDesc), len(file_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
