// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameAuthor = "author"

// Author mapped from table <author>
type Author struct {
	ID   int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(128);not null;comment:作者" json:"name"` // 作者
	Desc string `gorm:"column:desc;type:text;comment:介绍" json:"desc"`                  // 介绍
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
