package entity

const (
	ROOMSTATE_WAITING    = "WAITING"
	ROOMSTATE_PLAYING    = "PLAYING"
	ROOMSTATE_CLOSED     = "CLOSED"
	PLAYER_STATE_WAITING = "WAITING"
	PLAYER_STATE_READY   = "READY"
	PLAYER_STATE_FAILED  = "FAILED"
)
