// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameGameUser = "game_user"

// GameUser 飞花令用户表
type GameUser struct {
	ID            int32     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`              // 自增ID
	Username      string    `gorm:"column:username;type:varchar(64);not null;comment:用户名" json:"username"`                             // 用户名
	PasswordHash  string    `gorm:"column:password_hash;type:char(64);not null;comment:加密密码(SHA256)" json:"passwordHash"`              // 加密密码(SHA256)
	ThirdPartyID  string    `gorm:"column:third_party_id;type:varchar(128);comment:第三方登录ID（微信/QQ）" json:"thirdPartyId"`                // 第三方登录ID（微信/QQ）
	GameRounds    int32     `gorm:"column:game_rounds;type:int(10) unsigned;comment:总参与局数" json:"gameRounds"`                          // 总参与局数
	Score         int32     `gorm:"column:score;type:int(11);comment:当前积分" json:"score"`                                               // 当前积分
	Coins         int32     `gorm:"column:coins;type:int(10) unsigned;default:100;comment:游戏币（购买道具用）" json:"coins"`                    // 游戏币（购买道具用）
	GameRank      string    `gorm:"column:game_rank;type:enum('青铜','白银','黄金','铂金','钻石');default:青铜;comment:段位等级" json:"gameRank"`      // 段位等级
	CurrentRoomID string    `gorm:"column:current_room_id;type:varchar(36);comment:当前所在房间UUID" json:"currentRoomId"`                   // 当前所在房间UUID
	HighestStreak int32     `gorm:"column:highest_streak;type:smallint(5) unsigned;comment:最高连击次数" json:"highestStreak"`               // 最高连击次数
	Achievements  string    `gorm:"column:achievements;type:text;comment:成就徽章（如“百诗斩”“主题大师”）" json:"achievements"`                      // 成就徽章（如“百诗斩”“主题大师”）
	FriendList    string    `gorm:"column:friend_list;type:text;comment:好友ID列表" json:"friendList"`                                     // 好友ID列表
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:注册时间" json:"createdAt"` // 注册时间
	LastLogin     time.Time `gorm:"column:last_login;type:datetime;comment:最后登录时间" json:"lastLogin"`                                   // 最后登录时间
	AccountStatus string    `gorm:"column:account_status;type:enum('正常','冻结','违规');default:正常;comment:账号状态" json:"accountStatus"`      // 账号状态
	ThemeStats    string    `gorm:"column:theme_stats;type:text;comment:主题战绩（如{'月':32,'花':45}）" json:"themeStats"`                     // 主题战绩（如{"月":32,"花":45}）
	Items         string    `gorm:"column:items;type:text;comment:道具库存（如{'提示卡':3,'换字令':1}）" json:"items"`                              // 道具库存（如{"提示卡":3,"换字令":1}）
	GameHistory   string    `gorm:"column:game_history;type:text;comment:最近10局对战记录" json:"gameHistory"`                                // 最近10局对战记录
	UserID        string    `gorm:"column:user_id;type:varchar(32);not null;comment:USERID" json:"userId"`                             // USERID
}

// TableName GameUser's table name
func (*GameUser) TableName() string {
	return TableNameGameUser
}
