// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"encoding/json"
	"time"
)

const TableNameGameRoom = "game_room"

// GameRoom 游戏房间表
type GameRoom struct {
	ID             int64           `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	RoomID         string          `gorm:"column:room_id;type:varchar(32);not null;comment:短房间ID，4-7位数字" json:"roomId"`                               // 短房间ID，4-7位数字
	Status         string          `gorm:"column:status;type:enum('waiting','playing','closed');not null;default:waiting;comment:房间状态" json:"status"` // 房间状态
	MaxPlayers     int32           `gorm:"column:max_players;type:tinyint(3) unsigned;not null;default:4;comment:最大玩家数" json:"maxPlayers"`            // 最大玩家数
	CurrentPlayers int32           `gorm:"column:current_players;type:tinyint(3) unsigned;not null;comment:当前玩家数" json:"currentPlayers"`              // 当前玩家数
	Password       string          `gorm:"column:password;type:varchar(6);comment:房间密码，6位数字" json:"password"`                                         // 房间密码，6位数字
	MinLevel       int32           `gorm:"column:min_level;type:smallint(5) unsigned;comment:最低准入等级" json:"minLevel"`                                 // 最低准入等级
	CostItemID     int32           `gorm:"column:cost_item_id;type:int(11);comment:消耗道具ID" json:"costItemId"`                                         // 消耗道具ID
	CostAmount     int32           `gorm:"column:cost_amount;type:int(11);comment:消耗道具数量" json:"costAmount"`                                          // 消耗道具数量
	CreatedAt      time.Time       `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"`         // 创建时间
	GameMode       string          `gorm:"column:game_mode;type:varchar(32);not null;default:classic;comment:游戏模式" json:"gameMode"`                   // 游戏模式
	Slogan         string          `gorm:"column:slogan;type:varchar(32);comment:房间标语" json:"slogan"`                                                 // 房间标语
	OwnerID        string          `gorm:"column:owner_id;type:varchar(32);not null;comment:房主ID" json:"ownerId"`                                     // 房主ID
	PlayerList     json.RawMessage `gorm:"column:player_list;type:json;comment:玩家列表，存储玩家ID、准备状态等信息" json:"playerList"`                                // 玩家列表，存储玩家ID、准备状态等信息
	GatewayIP      string          `gorm:"column:gateway_ip;type:varchar(32);not null;default:127.0.0.1;comment:网关机器，IP地址" json:"gatewayIp"`          // 网关机器，IP地址
	Rounds         json.RawMessage `gorm:"column:rounds;type:json;comment:当前房间所有回合" json:"rounds"`
}

// TableName GameRoom's table name
func (*GameRoom) TableName() string {
	return TableNameGameRoom
}
