// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNamePoetryTag = "poetry_tag"

// PoetryTag 飞花令诗词标签表
type PoetryTag struct {
	ID       int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	PoetryID int64  `gorm:"column:poetry_id;type:bigint(20);not null;comment:诗词ID" json:"poetryId"`       // 诗词ID
	Tag      string `gorm:"column:tag;type:varchar(255);not null;comment:标签" json:"tag"`                  // 标签
	MinnTagID int64  `gorm:"column:min_tag_id;type:bigint(20);not null;comment:标签ID" json:"minTagId"`			  // 标签ID
}

// TableName PoetryTag's table name
func (*PoetryTag) TableName() string {
	return TableNamePoetryTag
}
