// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: poetry.proto

package poetry

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// PoetryService defines service.
type PoetryService interface {
	DescribePoetryInfo(ctx context.Context, req *DescribePoetryInfoRequest) (*DescribePoetryInfoResponse, error)
}

func PoetryService_DescribePoetryInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DescribePoetryInfoRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PoetryService).DescribePoetryInfo(ctx, reqbody.(*DescribePoetryInfoRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PoetryServer_ServiceDesc descriptor for server.RegisterService.
var PoetryServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.poetry.Poetry",
	HandlerType: ((*PoetryService)(nil)),
	Methods: []server.Method{
		{
			Name: "/poetry/DescribePoetryInfo",
			Func: PoetryService_DescribePoetryInfo_Handler,
		},
		{
			Name: "/trpc.poetry.Poetry/DescribePoetryInfo",
			Func: PoetryService_DescribePoetryInfo_Handler,
		},
	},
}

// RegisterPoetryService registers service.
func RegisterPoetryService(s server.Service, svr PoetryService) {
	if err := s.Register(&PoetryServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Poetry register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedPoetry struct{}

func (s *UnimplementedPoetry) DescribePoetryInfo(ctx context.Context, req *DescribePoetryInfoRequest) (*DescribePoetryInfoResponse, error) {
	return nil, errors.New("rpc DescribePoetryInfo of service Poetry is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// PoetryClientProxy defines service client proxy
type PoetryClientProxy interface {
	DescribePoetryInfo(ctx context.Context, req *DescribePoetryInfoRequest, opts ...client.Option) (rsp *DescribePoetryInfoResponse, err error)
}

type PoetryClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPoetryClientProxy = func(opts ...client.Option) PoetryClientProxy {
	return &PoetryClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PoetryClientProxyImpl) DescribePoetryInfo(ctx context.Context, req *DescribePoetryInfoRequest, opts ...client.Option) (*DescribePoetryInfoResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/poetry/DescribePoetryInfo")
	msg.WithCalleeServiceName(PoetryServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Poetry")
	msg.WithCalleeMethod("DescribePoetryInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DescribePoetryInfoResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
