// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: game_room.proto

package game_room

import (
	"poetry/pb/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "trpc.group/trpc/trpc-protocol/pb/go/trpc/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPlayers    int32                  `protobuf:"varint,1,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRoomRequest) Reset() {
	*x = CreateGameRoomRequest{}
	mi := &file_game_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRoomRequest) ProtoMessage() {}

func (x *CreateGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateGameRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateGameRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRoomResp) Reset() {
	*x = CreateGameRoomResp{}
	mi := &file_game_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRoomResp) ProtoMessage() {}

func (x *CreateGameRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRoomResp.ProtoReflect.Descriptor instead.
func (*CreateGameRoomResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameRoomResp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinGameRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRoomRequest) Reset() {
	*x = JoinGameRoomRequest{}
	mi := &file_game_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRoomRequest) ProtoMessage() {}

func (x *JoinGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinGameRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinGameRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameRoomResp) Reset() {
	*x = JoinGameRoomResp{}
	mi := &file_game_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRoomResp) ProtoMessage() {}

func (x *JoinGameRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRoomResp.ProtoReflect.Descriptor instead.
func (*JoinGameRoomResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameRoomResp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinGameRoomResp) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_game_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type DescribeGameRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        []*common.Filter       `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeGameRoomRequest) Reset() {
	*x = DescribeGameRoomRequest{}
	mi := &file_game_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeGameRoomRequest) ProtoMessage() {}

func (x *DescribeGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeGameRoomRequest.ProtoReflect.Descriptor instead.
func (*DescribeGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeGameRoomRequest) GetFilter() []*common.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DescribeGameRoomRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DescribeGameRoomRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GameRoomInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MaxPlayers     int32                  `protobuf:"varint,3,opt,name=maxPlayers,proto3" json:"maxPlayers,omitempty"`
	CurrentPlayers int32                  `protobuf:"varint,4,opt,name=currentPlayers,proto3" json:"currentPlayers,omitempty"`
	GameMode       string                 `protobuf:"bytes,5,opt,name=gameMode,proto3" json:"gameMode,omitempty"`
	Slogan         string                 `protobuf:"bytes,6,opt,name=slogan,proto3" json:"slogan,omitempty"`
	OwnerId        string                 `protobuf:"bytes,7,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	PlayerList     []*Player              `protobuf:"bytes,8,rep,name=playerList,proto3" json:"playerList,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameRoomInfo) Reset() {
	*x = GameRoomInfo{}
	mi := &file_game_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRoomInfo) ProtoMessage() {}

func (x *GameRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRoomInfo.ProtoReflect.Descriptor instead.
func (*GameRoomInfo) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{6}
}

func (x *GameRoomInfo) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameRoomInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GameRoomInfo) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameRoomInfo) GetCurrentPlayers() int32 {
	if x != nil {
		return x.CurrentPlayers
	}
	return 0
}

func (x *GameRoomInfo) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *GameRoomInfo) GetSlogan() string {
	if x != nil {
		return x.Slogan
	}
	return ""
}

func (x *GameRoomInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GameRoomInfo) GetPlayerList() []*Player {
	if x != nil {
		return x.PlayerList
	}
	return nil
}

type DescribeGameRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameRoomList  []*GameRoomInfo        `protobuf:"bytes,1,rep,name=gameRoomList,proto3" json:"gameRoomList,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeGameRoomResp) Reset() {
	*x = DescribeGameRoomResp{}
	mi := &file_game_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeGameRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeGameRoomResp) ProtoMessage() {}

func (x *DescribeGameRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeGameRoomResp.ProtoReflect.Descriptor instead.
func (*DescribeGameRoomResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeGameRoomResp) GetGameRoomList() []*GameRoomInfo {
	if x != nil {
		return x.GameRoomList
	}
	return nil
}

func (x *DescribeGameRoomResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type LeaveGameRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameRoomRequest) Reset() {
	*x = LeaveGameRoomRequest{}
	mi := &file_game_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameRoomRequest) ProtoMessage() {}

func (x *LeaveGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{8}
}

type LeaveGameRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGameRoomResp) Reset() {
	*x = LeaveGameRoomResp{}
	mi := &file_game_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGameRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGameRoomResp) ProtoMessage() {}

func (x *LeaveGameRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGameRoomResp.ProtoReflect.Descriptor instead.
func (*LeaveGameRoomResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{9}
}

type ReadyGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyGameRequest) Reset() {
	*x = ReadyGameRequest{}
	mi := &file_game_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyGameRequest) ProtoMessage() {}

func (x *ReadyGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyGameRequest.ProtoReflect.Descriptor instead.
func (*ReadyGameRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{10}
}

func (x *ReadyGameRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ReadyGameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyGameResp) Reset() {
	*x = ReadyGameResp{}
	mi := &file_game_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyGameResp) ProtoMessage() {}

func (x *ReadyGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyGameResp.ProtoReflect.Descriptor instead.
func (*ReadyGameResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{11}
}

func (x *ReadyGameResp) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type SubmitPoetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Poetry        string                 `protobuf:"bytes,1,opt,name=poetry,proto3" json:"poetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPoetryRequest) Reset() {
	*x = SubmitPoetryRequest{}
	mi := &file_game_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPoetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPoetryRequest) ProtoMessage() {}

func (x *SubmitPoetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPoetryRequest.ProtoReflect.Descriptor instead.
func (*SubmitPoetryRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitPoetryRequest) GetPoetry() string {
	if x != nil {
		return x.Poetry
	}
	return ""
}

type NanoJoinGameRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NanoJoinGameRoomRequest) Reset() {
	*x = NanoJoinGameRoomRequest{}
	mi := &file_game_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NanoJoinGameRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NanoJoinGameRoomRequest) ProtoMessage() {}

func (x *NanoJoinGameRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NanoJoinGameRoomRequest.ProtoReflect.Descriptor instead.
func (*NanoJoinGameRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{13}
}

func (x *NanoJoinGameRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NanoJoinGameRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *NanoJoinGameRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NanoJoinGameRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NanoJoinGameRoomResp) Reset() {
	*x = NanoJoinGameRoomResp{}
	mi := &file_game_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NanoJoinGameRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NanoJoinGameRoomResp) ProtoMessage() {}

func (x *NanoJoinGameRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_game_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NanoJoinGameRoomResp.ProtoReflect.Descriptor instead.
func (*NanoJoinGameRoomResp) Descriptor() ([]byte, []int) {
	return file_game_room_proto_rawDescGZIP(), []int{14}
}

func (x *NanoJoinGameRoomResp) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_game_room_proto protoreflect.FileDescriptor

const file_game_room_proto_rawDesc = "" +
	"\n" +
	"\x0fgame_room.proto\x12\ttrpc.game\x1a\fcommon.proto\x1a\x1dtrpc/proto/trpc_options.proto\"S\n" +
	"\x15CreateGameRoomRequest\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x01 \x01(\x05R\n" +
	"maxPlayers\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\",\n" +
	"\x12CreateGameRoomResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"I\n" +
	"\x13JoinGameRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\x10JoinGameRoomResp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12+\n" +
	"\aplayers\x18\x02 \x03(\v2\x11.trpc.game.PlayerR\aplayers\"R\n" +
	"\x06Player\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"o\n" +
	"\x17DescribeGameRoomRequest\x12&\n" +
	"\x06filter\x18\x01 \x03(\v2\x0e.common.FilterR\x06filter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x87\x02\n" +
	"\fGameRoomInfo\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"maxPlayers\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12&\n" +
	"\x0ecurrentPlayers\x18\x04 \x01(\x05R\x0ecurrentPlayers\x12\x1a\n" +
	"\bgameMode\x18\x05 \x01(\tR\bgameMode\x12\x16\n" +
	"\x06slogan\x18\x06 \x01(\tR\x06slogan\x12\x18\n" +
	"\aownerId\x18\a \x01(\tR\aownerId\x121\n" +
	"\n" +
	"playerList\x18\b \x03(\v2\x11.trpc.game.PlayerR\n" +
	"playerList\"s\n" +
	"\x14DescribeGameRoomResp\x12;\n" +
	"\fgameRoomList\x18\x01 \x03(\v2\x17.trpc.game.GameRoomInfoR\fgameRoomList\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x16\n" +
	"\x14LeaveGameRoomRequest\"\x13\n" +
	"\x11LeaveGameRoomResp\"(\n" +
	"\x10ReadyGameRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\":\n" +
	"\rReadyGameResp\x12)\n" +
	"\x06player\x18\x01 \x01(\v2\x11.trpc.game.PlayerR\x06player\"-\n" +
	"\x13SubmitPoetryRequest\x12\x16\n" +
	"\x06poetry\x18\x01 \x01(\tR\x06poetry\"c\n" +
	"\x17NanoJoinGameRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\",\n" +
	"\x14NanoJoinGameRoomResp\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state2\xc2\x03\n" +
	"\bGameRoom\x12m\n" +
	"\x0eCreateGameRoom\x12 .trpc.game.CreateGameRoomRequest\x1a\x1d.trpc.game.CreateGameRoomResp\"\x1a\x8a\xb5\x18\x16/poetry/CreateGameRoom\x12e\n" +
	"\fJoinGameRoom\x12\x1e.trpc.game.JoinGameRoomRequest\x1a\x1b.trpc.game.JoinGameRoomResp\"\x18\x8a\xb5\x18\x14/poetry/JoinGameRoom\x12u\n" +
	"\x10DescribeGameRoom\x12\".trpc.game.DescribeGameRoomRequest\x1a\x1f.trpc.game.DescribeGameRoomResp\"\x1c\x8a\xb5\x18\x18/poetry/DescribeGameRoom\x12i\n" +
	"\rLeaveGameRoom\x12\x1f.trpc.game.LeaveGameRoomRequest\x1a\x1c.trpc.game.LeaveGameRoomResp\"\x19\x8a\xb5\x18\x15/poetry/LeaveGameRoomB\x0eZ\fpb/game_roomb\x06proto3"

var (
	file_game_room_proto_rawDescOnce sync.Once
	file_game_room_proto_rawDescData []byte
)

func file_game_room_proto_rawDescGZIP() []byte {
	file_game_room_proto_rawDescOnce.Do(func() {
		file_game_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_room_proto_rawDesc), len(file_game_room_proto_rawDesc)))
	})
	return file_game_room_proto_rawDescData
}

var file_game_room_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_room_proto_goTypes = []any{
	(*CreateGameRoomRequest)(nil),   // 0: trpc.game.CreateGameRoomRequest
	(*CreateGameRoomResp)(nil),      // 1: trpc.game.CreateGameRoomResp
	(*JoinGameRoomRequest)(nil),     // 2: trpc.game.JoinGameRoomRequest
	(*JoinGameRoomResp)(nil),        // 3: trpc.game.JoinGameRoomResp
	(*Player)(nil),                  // 4: trpc.game.Player
	(*DescribeGameRoomRequest)(nil), // 5: trpc.game.DescribeGameRoomRequest
	(*GameRoomInfo)(nil),            // 6: trpc.game.GameRoomInfo
	(*DescribeGameRoomResp)(nil),    // 7: trpc.game.DescribeGameRoomResp
	(*LeaveGameRoomRequest)(nil),    // 8: trpc.game.LeaveGameRoomRequest
	(*LeaveGameRoomResp)(nil),       // 9: trpc.game.LeaveGameRoomResp
	(*ReadyGameRequest)(nil),        // 10: trpc.game.ReadyGameRequest
	(*ReadyGameResp)(nil),           // 11: trpc.game.ReadyGameResp
	(*SubmitPoetryRequest)(nil),     // 12: trpc.game.SubmitPoetryRequest
	(*NanoJoinGameRoomRequest)(nil), // 13: trpc.game.NanoJoinGameRoomRequest
	(*NanoJoinGameRoomResp)(nil),    // 14: trpc.game.NanoJoinGameRoomResp
	(*common.Filter)(nil),           // 15: common.Filter
}
var file_game_room_proto_depIdxs = []int32{
	4,  // 0: trpc.game.JoinGameRoomResp.players:type_name -> trpc.game.Player
	15, // 1: trpc.game.DescribeGameRoomRequest.filter:type_name -> common.Filter
	4,  // 2: trpc.game.GameRoomInfo.playerList:type_name -> trpc.game.Player
	6,  // 3: trpc.game.DescribeGameRoomResp.gameRoomList:type_name -> trpc.game.GameRoomInfo
	4,  // 4: trpc.game.ReadyGameResp.player:type_name -> trpc.game.Player
	0,  // 5: trpc.game.GameRoom.CreateGameRoom:input_type -> trpc.game.CreateGameRoomRequest
	2,  // 6: trpc.game.GameRoom.JoinGameRoom:input_type -> trpc.game.JoinGameRoomRequest
	5,  // 7: trpc.game.GameRoom.DescribeGameRoom:input_type -> trpc.game.DescribeGameRoomRequest
	8,  // 8: trpc.game.GameRoom.LeaveGameRoom:input_type -> trpc.game.LeaveGameRoomRequest
	1,  // 9: trpc.game.GameRoom.CreateGameRoom:output_type -> trpc.game.CreateGameRoomResp
	3,  // 10: trpc.game.GameRoom.JoinGameRoom:output_type -> trpc.game.JoinGameRoomResp
	7,  // 11: trpc.game.GameRoom.DescribeGameRoom:output_type -> trpc.game.DescribeGameRoomResp
	9,  // 12: trpc.game.GameRoom.LeaveGameRoom:output_type -> trpc.game.LeaveGameRoomResp
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_game_room_proto_init() }
func file_game_room_proto_init() {
	if File_game_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_room_proto_rawDesc), len(file_game_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_room_proto_goTypes,
		DependencyIndexes: file_game_room_proto_depIdxs,
		MessageInfos:      file_game_room_proto_msgTypes,
	}.Build()
	File_game_room_proto = out.File
	file_game_room_proto_goTypes = nil
	file_game_room_proto_depIdxs = nil
}
